version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: quickstart
    ports:
      - 80:80
    volumes:
      - .:/app/php
    links:
      - mysql
    environment:
        DB_HOST: mysql
        DB_DATABASE: quickstart
        DB_USERNAME: quickstart_user
        DB_PASSWORD: quickstart_password
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: quickstart
      MYSQL_USER: quickstart_user
      MYSQL_PASSWORD: quickstart_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./app/mysql/data:/var/lib/mysql
